refactor(pillar): sync map.jinja with template-formula
saltstack-formulas/timezone-formula pull request #17
Opened 2019-08-27 21:04 UTC by n-rodriguez

2019-08-30 22:07 UTC, noelmcloughlin requested changes
Looks pretty good @n-rodriguez  thank you for PR
I have just one requested change.  
Could you update  `pillar.example` showing `pkg.name` instead of `pkgname` too.

2019-08-30 22:07 UTC, noelmcloughlin commented on timezone/init.sls
> +    - name: {{ timezone.pkgname }}
This should be `timezone.pkg.name` because `pkg` will be a dict in template-formula.

2019-08-30 22:07 UTC, noelmcloughlin commented on timezone/init.sls
> +      - pkg: {{ timezone.pkgname }}
same

2019-08-31 22:44 UTC, n-rodriguez commented
>  Could you update `pillar.example` showing `pkg.name` instead of `pkgname` too.

Well.. actually the goal of this PR was to add semantic-release without introducing any changes that could break behaviors.

2019-09-01 00:15 UTC, noelmcloughlin approved these changes
Thanks @n-rodriguez !!

2019-09-01 08:26 UTC, merged